name: Core
version: '${project.version}'
main: org.aledev.core.Core
api-version: '1.20'
commands:
  balance:
    aliases: ["bal"]
    description: "Show your or a player's balance."
    usage: "/bal <set|add|remove|> <player> <quantity>"
  pay:
    description: "Lets you pay money to another player."
    usage: "/pay <player> <quantity>"